// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestProtobuf.proto
// Protobuf C++ Version: 4.26.0-dev

#include "RequestProtobuf.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace protobuf {

inline constexpr RequestProtobuf::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sign_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        serverid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cmdtype_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RequestProtobuf::RequestProtobuf(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RequestProtobufDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RequestProtobufDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RequestProtobufDefaultTypeInternal() {}
  union {
    RequestProtobuf _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RequestProtobufDefaultTypeInternal _RequestProtobuf_default_instance_;
}  // namespace protobuf
static ::_pb::Metadata file_level_metadata_RequestProtobuf_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_RequestProtobuf_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_RequestProtobuf_2eproto = nullptr;
const ::uint32_t
    TableStruct_RequestProtobuf_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::protobuf::RequestProtobuf, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::protobuf::RequestProtobuf, _impl_.cmdtype_),
        PROTOBUF_FIELD_OFFSET(::protobuf::RequestProtobuf, _impl_.clientid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::RequestProtobuf, _impl_.sign_),
        PROTOBUF_FIELD_OFFSET(::protobuf::RequestProtobuf, _impl_.serverid_),
        PROTOBUF_FIELD_OFFSET(::protobuf::RequestProtobuf, _impl_.data_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::protobuf::RequestProtobuf)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::protobuf::_RequestProtobuf_default_instance_._instance,
};
const char descriptor_table_protodef_RequestProtobuf_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025RequestProtobuf.proto\022\010protobuf\"b\n\017Req"
    "uestProtobuf\022\017\n\007cmdType\030\001 \001(\005\022\020\n\010clientI"
    "d\030\002 \001(\014\022\014\n\004sign\030\003 \001(\014\022\020\n\010serverId\030\004 \001(\014\022"
    "\014\n\004data\030\005 \001(\014b\006proto3"
};
static ::absl::once_flag descriptor_table_RequestProtobuf_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_RequestProtobuf_2eproto = {
    false,
    false,
    141,
    descriptor_table_protodef_RequestProtobuf_2eproto,
    "RequestProtobuf.proto",
    &descriptor_table_RequestProtobuf_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_RequestProtobuf_2eproto::offsets,
    file_level_metadata_RequestProtobuf_2eproto,
    file_level_enum_descriptors_RequestProtobuf_2eproto,
    file_level_service_descriptors_RequestProtobuf_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_RequestProtobuf_2eproto_getter() {
  return &descriptor_table_RequestProtobuf_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_RequestProtobuf_2eproto(&descriptor_table_RequestProtobuf_2eproto);
namespace protobuf {
// ===================================================================

class RequestProtobuf::_Internal {
 public:
};

RequestProtobuf::RequestProtobuf(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:protobuf.RequestProtobuf)
}
inline PROTOBUF_NDEBUG_INLINE RequestProtobuf::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : clientid_(arena, from.clientid_),
        sign_(arena, from.sign_),
        serverid_(arena, from.serverid_),
        data_(arena, from.data_),
        _cached_size_{0} {}

RequestProtobuf::RequestProtobuf(
    ::google::protobuf::Arena* arena,
    const RequestProtobuf& from)
    : ::google::protobuf::Message(arena) {
  RequestProtobuf* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.cmdtype_ = from._impl_.cmdtype_;

  // @@protoc_insertion_point(copy_constructor:protobuf.RequestProtobuf)
}
inline PROTOBUF_NDEBUG_INLINE RequestProtobuf::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : clientid_(arena),
        sign_(arena),
        serverid_(arena),
        data_(arena),
        _cached_size_{0} {}

inline void RequestProtobuf::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.cmdtype_ = {};
}
RequestProtobuf::~RequestProtobuf() {
  // @@protoc_insertion_point(destructor:protobuf.RequestProtobuf)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RequestProtobuf::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.clientid_.Destroy();
  _impl_.sign_.Destroy();
  _impl_.serverid_.Destroy();
  _impl_.data_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
RequestProtobuf::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      _data_ = {
          RequestProtobuf::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
              PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_._cached_size_),
      };
  return &_data_;
}
PROTOBUF_NOINLINE void RequestProtobuf::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf.RequestProtobuf)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clientid_.ClearToEmpty();
  _impl_.sign_.ClearToEmpty();
  _impl_.serverid_.ClearToEmpty();
  _impl_.data_.ClearToEmpty();
  _impl_.cmdtype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RequestProtobuf::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 0, 2> RequestProtobuf::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RequestProtobuf_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::protobuf::RequestProtobuf>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 cmdType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RequestProtobuf, _impl_.cmdtype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.cmdtype_)}},
    // bytes clientId = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.clientid_)}},
    // bytes sign = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.sign_)}},
    // bytes serverId = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.serverid_)}},
    // bytes data = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.data_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 cmdType = 1;
    {PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.cmdtype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // bytes clientId = 2;
    {PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.clientid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes sign = 3;
    {PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.sign_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes serverId = 4;
    {PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.serverid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes data = 5;
    {PROTOBUF_FIELD_OFFSET(RequestProtobuf, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* RequestProtobuf::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf.RequestProtobuf)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 cmdType = 1;
  if (this->_internal_cmdtype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_cmdtype(), target);
  }

  // bytes clientId = 2;
  if (!this->_internal_clientid().empty()) {
    const std::string& _s = this->_internal_clientid();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // bytes sign = 3;
  if (!this->_internal_sign().empty()) {
    const std::string& _s = this->_internal_sign();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  // bytes serverId = 4;
  if (!this->_internal_serverid().empty()) {
    const std::string& _s = this->_internal_serverid();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  // bytes data = 5;
  if (!this->_internal_data().empty()) {
    const std::string& _s = this->_internal_data();
    target = stream->WriteBytesMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf.RequestProtobuf)
  return target;
}

::size_t RequestProtobuf::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf.RequestProtobuf)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes clientId = 2;
  if (!this->_internal_clientid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_clientid());
  }

  // bytes sign = 3;
  if (!this->_internal_sign().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_sign());
  }

  // bytes serverId = 4;
  if (!this->_internal_serverid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_serverid());
  }

  // bytes data = 5;
  if (!this->_internal_data().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_data());
  }

  // int32 cmdType = 1;
  if (this->_internal_cmdtype() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_cmdtype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void RequestProtobuf::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RequestProtobuf*>(&to_msg);
  auto& from = static_cast<const RequestProtobuf&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf.RequestProtobuf)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_clientid().empty()) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  if (!from._internal_sign().empty()) {
    _this->_internal_set_sign(from._internal_sign());
  }
  if (!from._internal_serverid().empty()) {
    _this->_internal_set_serverid(from._internal_serverid());
  }
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_cmdtype() != 0) {
    _this->_internal_set_cmdtype(from._internal_cmdtype());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RequestProtobuf::CopyFrom(const RequestProtobuf& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf.RequestProtobuf)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RequestProtobuf::IsInitialized() const {
  return true;
}

void RequestProtobuf::InternalSwap(RequestProtobuf* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sign_, &other->_impl_.sign_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.serverid_, &other->_impl_.serverid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
        swap(_impl_.cmdtype_, other->_impl_.cmdtype_);
}

::google::protobuf::Metadata RequestProtobuf::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_RequestProtobuf_2eproto_getter, &descriptor_table_RequestProtobuf_2eproto_once,
      file_level_metadata_RequestProtobuf_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
